spring.application.name=config-server
server.port=8889

#------- Where to read configs from
#Option A: local file system(dev/learning)
spring.cloud.config.server.native.search-locations=classpath:/config-repo
spring.profiles.active=native

#Option B: Git repo (production - change history, branches, PRS)
spring.cloud.config.server.git.uri=https://github.com/bandenawaz/university-portal/config-repo
spring.cloud.config.server.git.clone-on-start=false
spring.cloud.config.server.git.default-label=main

#Register with Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
