#Shared DB config pattern(each service overrides with its own db name)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Shared JWT secret - ALL services use the same secret to verify tokens
jwt.secret=university-super-secret-key-must-be-at-least-256-bits-long
jwt.expiration=86400000

#Share actuator config
management.endpoints.web.exposure.include=*
management.endpoints.health.show-deatils=always