
#Course-service specific properties
spring.application.name=course-service
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/course_db
spring.datasource.username=root
spring.datasource.password=root@123
info.app.name= University Course Service
info.app.version=1.0.0