spring.application.name=eureka-server

#Standard Port for Eureka Server
server.port=8761

eureka.instance.hostname=localhost
#This is the server, so it should not register with itself
eureka.client.register-with-eureka=false
#It should not fetch registry from itself
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true

eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka


