spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=university-super-secret-key-must-be-at-least-256-bits-long

#Logging for debugging and route matching
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG

spring.cloud.compatibility-verifier.enabled=false
